language: node_js
node_js:
  - "10"
dist: trusty
sudo: required
branches:
  only:
  - master
before_script:
  - npm install -g @angular/cli
script:
- ng lint
- ng build --prod --base-href https://jobjingjo.github.io/angularTest/
- npm run test --coverage

after_script:
  - COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN npm run coveralls

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: dist/angularTest
    on:
      branch: master